namespace: finbank

image:
  registry: "744376745946.dkr.ecr.ap-south-1.amazonaws.com/finops-data-platform"
  tag: af2216429d343f373e189d60f1676dc34fc12526
  pullPolicy: IfNotPresent

services:
  accountService:
    name: account-service
    port: 8080
    replicas: 2
  transactionService:
    name: transaction-service
    port: 8080
    replicas: 2
  loanService:
    name: loan-service
    port: 8080
    replicas: 2
  fraudService:
    name: fraud-service
    port: 8080
    replicas: 2

ingress:
  enabled: true
  className: alb
  host: finbank.example.com
