namespace: finbank

image:
  registry: "744376745946.dkr.ecr.ap-south-1.amazonaws.com/finops-data-platform"
  tag: b8995f80ebe2f95d646a9dfbad9562780c84c620
  pullPolicy: IfNotPresent

services:
  accountService:
    name: account-service
    port: 8080
    replicas: 2
  transactionService:
    name: transaction-service
    port: 8080
    replicas: 2
  loanService:
    name: loan-service
    port: 8080
    replicas: 2
  fraudService:
    name: fraud-service
    port: 8080
    replicas: 2

ingress:
  enabled: true
  className: alb
  host: finbank.example.com
