{{- range $key, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - port: 80
      targetPort: {{ $svc.port }}
---
{{- end }}
